name: deploy-mistaker-demo

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run Tests
        run: make all

  deploy-dev:
    name: deploy-dev
    needs: run-tests
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Plan
        working-directory: terraform
        run: terraform plan
      - name: Apply
        working-directory: terraform
        run: terraform apply -auto-approve
      - name: Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
